name: edna2obis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas
  - numpy
  - openpyxl
  - pyworms
  - multiprocess
  - pygbif
  - pytz
  - pyyaml
  - notebook
  - nb_conda_kernels
  - rich
  - pyfiglet
